import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    /*  if (kIsWeb) {
      return web;
    }*/
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      // case TargetPlatform.macOS:
      //   return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

/*
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDydIyZ67EH_BPVoGvuFOELSsz77a7-uj0',
    appId: '1:910516599381:web:1e849d6f34aad5d13c72dc',
    messagingSenderId: '910516599381',
    projectId: 'udemy-ac28e',
    authDomain: 'udemy-ac28e.firebaseapp.com',
    storageBucket: 'udemy-ac28e.appspot.com',
    measurementId: 'G-Z2CQWBK39Q',
  );
*/

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn2qMEhOZSy-Ow1NERPhbayoxMN8bSzRE',
    appId: '1:1071357302433:android:0430a619877a1b3449c2e0',
    messagingSenderId: '1071357302433',
    projectId: 'tvnine-8fd2a',
    storageBucket: 'tvnine-8fd2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN-_wEfq1aFVjSeNtvI734iH_6lGSG9to',
    appId: '1:1071357302433:ios:8e52801b03e4517a49c2e0',
    messagingSenderId: '1071357302433',
    projectId: 'tvnine-8fd2a',
    storageBucket: 'tvnine-8fd2a.appspot.com',
    androidClientId:
        '1071357302433-4osfvg0mb6hnvm62gec3kr6lcberbldb.apps.googleusercontent.com',
    iosClientId:
        '1071357302433-l8gb5qqbrfqd1lfk0snacnoa2mjsh88e.apps.googleusercontent.com',
    iosBundleId: 'com.androdev.assignment.satyamAssignment',
  );
}

/*
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn2qMEhOZSy-Ow1NERPhbayoxMN8bSzRE',
    appId: '1:1071357302433:android:0430a619877a1b3449c2e0',
    messagingSenderId: '1071357302433',
    projectId: 'tvnine-8fd2a',
    storageBucket: 'tvnine-8fd2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN-_wEfq1aFVjSeNtvI734iH_6lGSG9to',
    appId: '1:1071357302433:ios:8e52801b03e4517a49c2e0',
    messagingSenderId: '1071357302433',
    projectId: 'tvnine-8fd2a',
    storageBucket: 'tvnine-8fd2a.appspot.com',
    androidClientId: '1071357302433-4osfvg0mb6hnvm62gec3kr6lcberbldb.apps.googleusercontent.com',
    iosClientId: '1071357302433-l8gb5qqbrfqd1lfk0snacnoa2mjsh88e.apps.googleusercontent.com',
    iosBundleId: 'com.androdev.assignment.satyamAssignment',
  );
}
*/
